changing text description color and add external link icon
Indie-Hackers-Brasil/mvp-website pull request #6
Opened 2024-07-31 17:05 UTC by trindadematheus

2024-07-31 18:34 UTC, Rychillie requested changes

2024-07-31 18:34 UTC, Rychillie commented on src/app/projetos/page.tsx
> +                      stroke-width="2"
ao invés de `stroke-width` use `strokeWidth`

2024-07-31 18:34 UTC, Rychillie commented on src/app/projetos/page.tsx
> +                      stroke-linecap="round"
ao invés de `stroke-linecap` use `strokeLinecap`

2024-07-31 18:34 UTC, Rychillie commented on src/app/projetos/page.tsx
> +                      stroke-linejoin="round"
ao invés de `stroke-linejoin` use `strokeLinejoin`

2024-07-31 18:34 UTC, Rychillie commented on src/app/sobre/page.tsx
> +      <p className='text-neutral-400'>Em desenvolvimento.</p>
mudar de `text-neutral-400` para `text-neutral-600 dark:text-neutral-400` para termos acessibilidade e dark mode funcionando

<img width="93" alt="Screenshot 2024-07-31 at 15 26 14" src="https://github.com/user-attachments/assets/f275e7da-d988-46aa-b95e-36777e2ab27c">

2024-07-31 18:34 UTC, Rychillie commented on src/app/projetos/page.tsx
> +              <p className="text-sm text-neutral-400">{project.descricao}</p>
mudar de `text-neutral-400` para `text-neutral-600 dark:text-neutral-400` para termos acessibilidade e dark mode funcionando

<img width="93" alt="Screenshot 2024-07-31 at 15 26 14" src="https://github.com/user-attachments/assets/f275e7da-d988-46aa-b95e-36777e2ab27c">

2024-07-31 18:34 UTC, Rychillie commented on src/app/ideias/page.tsx
> +      <p className='text-neutral-400'>Conheça as ideias de produtos digitais brasileiros.</p>
mudar de `text-neutral-400` para `text-neutral-600 dark:text-neutral-400` para termos acessibilidade e dark mode funcionando

<img width="93" alt="Screenshot 2024-07-31 at 15 26 14" src="https://github.com/user-attachments/assets/f275e7da-d988-46aa-b95e-36777e2ab27c">

2024-07-31 18:34 UTC, Rychillie commented on src/app/criadores/page.tsx
> +      <p className='text-neutral-400'>Conheça os criadores de produtos digitais brasileiros.</p>
mudar de `text-neutral-400` para `text-neutral-600 dark:text-neutral-400` para termos acessibilidade e dark mode funcionando

<img width="93" alt="Screenshot 2024-07-31 at 15 26 14" src="https://github.com/user-attachments/assets/f275e7da-d988-46aa-b95e-36777e2ab27c">

2024-07-31 18:34 UTC, Rychillie commented on src/app/projetos/page.tsx
> +            <div className="group flex flex-col gap-2 rounded-lg border border-neutral-200 p-4 shadow-sm transition-all hover:scale-105 hover:border-violet-500 hover:shadow-md dark:border-neutral-800
por favor poderia adicionar o Hover e o group no link

2024-07-31 18:34 UTC, Rychillie commented on src/app/projetos/page.tsx
> +                      stroke="#a3a3a3"
poderia mudar o stroke para o `stroke="currentColor"` assim ele recebera a cor do pai

2024-07-31 18:34 UTC, Rychillie commented on src/app/projetos/page.tsx
> +                <svg className="hidden group-hover:block" xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 24 24" fill="none">
pode adicionar uma classe `text-violet-500`no SVG para deixar ele filé? 👌

2024-07-31 21:03 UTC, birobirobiro commented on src/app/projetos/page.tsx
> +                <svg className="hidden group-hover:block" xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 24 24" fill="none">
Ao invés de usar um SVG não seria interessante já instalar uma lib como lucide-react por exemplo para futuros ícones?

2024-07-31 21:08 UTC, trindadematheus commented on src/app/projetos/page.tsx
> +                <svg className="hidden group-hover:block" xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" viewBox="0 0 24 24" fill="none">
Eu pensei em instalar uma lib mas como o projeto está no começo preferi não instalar nada

2024-07-31 21:17 UTC, Rychillie approved these changes

2024-08-01 12:17 UTC, birobirobiro approved these changes

2024-08-01 12:17 UTC, merged